env:
  browser: true
  commonjs: true
  es6: true
  jest: true
ecmaFeatures:
  modules: true
  spread: true
  restParams: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
  comma-dangle: off
  no-unused-vars: warn
  no-console: error
  no-unexpected-multiline: warn
  import/prefer-default-export: off
settings:
  react:
    pragma: React
    version: detect
